directories:
  rootdir_lung: /nas-ctm01/datasets/public/medical_datasets/lung_ct_datasets/nlst/preprocessed_data/protocol_5/2d/lung
  rootdir_ws: /nas-ctm01/datasets/public/medical_datasets/lung_ct_datasets/nlst/preprocessed_data/protocol_5/2d/ws
  rootdir_masked: /nas-ctm01/datasets/public/medical_datasets/lung_ct_datasets/nlst/preprocessed_data/protocol_5/2d/masked
  image_df_path: /nas-ctm01/homes/fmferreira/AI4LUNGS/lung_file_paths.csv
  cancer_path: /nas-ctm01/datasets/public/medical_datasets/lung_ct_datasets/nlst/cancer_info_final_mapped.csv
data:
  columns:
    pid: pid
    file_path: file_path

SEED: 22
test_size: 0.2

BATCH_SIZE_CPU: 32
BATCH_SIZE_GPU: 128
EPOCHS: 300
LEARNING_RATE: 1e-5

wandb:
  project: AI4H-Code
  entity: nlst
  name: test-embeddings

hyperparameter:
  method: grid 
  metric:
    name: test_auc
    goal: maximize
  parameters:
    learning_rate:
      values: [0.00001, 0.0001, 0.001, 0.01, 0.1]
    epochs:
      values: [100, 200, 300, 400, 500]
    batch_size:
      values: [32, 64, 128]