wandb_version: 1

learning_rate:
  desc: null
  value: 0.0001
epochs:
  desc: null
  value: 100
batch_size:
  desc: null
  value: 32
model_type:
  desc: null
  value: MLP_Cox
_wandb:
  desc: null
  value:
    python_version: 3.11.14
    cli_version: 0.15.2
    framework: huggingface
    huggingface_version: 4.28.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1764873762.574202
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 50
      - 53
      - 55
      - 63
      2:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 50
      - 53
      - 55
      - 63
      3:
      - 2
      - 7
      - 13
      - 16
      - 23
      4: 3.11.14
      5: 0.15.2
      6: 4.28.0
      8:
      - 5
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: val_loss
      5: 1
      6:
      - 1
    - 1: val_auroc
      5: 1
      6:
      - 1
    - 1: val_f1_score
      5: 1
      6:
      - 1
    - 1: val_balanced_accuracy
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: train_loss
      5: 1
      6:
      - 1
    - 1: test_auroc
      5: 1
      6:
      - 1
    - 1: test_f1_score
      5: 1
      6:
      - 1
    - 1: test_balanced_accuracy
      5: 1
      6:
      - 1
