name: ai4lungs
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.4=h06a4308_0
  - expat=2.7.3=h3385a95_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.11.14=h6fa692b_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py311h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py311h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - accessible-pygments==0.0.5
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - alabaster==0.7.16
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - astroid==3.0.3
      - asttokens==3.0.1
      - attrs==25.4.0
      - autograd==1.8.0
      - autograd-gamma==0.5.0
      - babel==2.17.0
      - backports-tarfile==1.2.0
      - beautifulsoup4==4.14.2
      - black==24.2.0
      - bleach==6.3.0
      - certifi==2025.11.12
      - cffi==2.0.0
      - cfgv==3.5.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - contourpy==1.3.3
      - cryptography==46.0.3
      - cycler==0.12.1
      - decorator==5.2.1
      - defusedxml==0.7.1
      - dill==0.4.0
      - distlib==0.4.0
      - docker-pycreds==0.4.0
      - docutils==0.20.1
      - ecos==2.0.14
      - einops==0.8.1
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - filelock==3.20.0
      - fonttools==4.60.1
      - formulaic==1.2.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - fvcore==0.1.5.post20221221
      - gitdb==4.0.12
      - gitpython==3.1.45
      - huggingface-hub==0.13.4
      - hydra-core==1.3.2
      - identify==2.6.15
      - idna==3.11
      - imagesize==1.4.1
      - importlib-metadata==8.7.0
      - interface-meta==1.3.0
      - iopath==0.1.10
      - ipython==8.20.0
      - isort==5.13.2
      - jaraco-classes==3.4.0
      - jaraco-context==6.0.1
      - jaraco-functools==4.3.0
      - jedi==0.19.2
      - jeepney==0.9.0
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.6.3
      - jupyter-core==5.9.1
      - jupyterlab-pygments==0.3.0
      - keyring==25.7.0
      - kiwisolver==1.4.9
      - latexcodec==3.0.1
      - lifelines==0.27.8
      - lightning==2.5.6
      - lightning-utilities==0.15.2
      - loguru==0.7.2
      - markdown-it-py==3.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - matplotlib-inline==0.2.1
      - mccabe==0.7.0
      - mdit-py-plugins==0.5.0
      - mdurl==0.1.2
      - mistune==3.1.4
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - multidict==6.7.0
      - mup==1.0.0
      - mypy==1.8.0
      - mypy-extensions==1.1.0
      - myst-parser==2.0.0
      - narwhals==2.12.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nbsphinx==0.9.3
      - networkx==3.6
      - nh3==0.3.2
      - nodeenv==1.9.1
      - numexpr==2.14.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - osqp==1.0.5
      - packaging==25.0
      - pandas==2.2.0
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pathspec==0.12.1
      - pathtools==0.1.2
      - pep517==0.13.0
      - pexpect==4.9.0
      - pillow==12.0.0
      - pkginfo==1.12.1.2
      - platformdirs==4.5.0
      - portalocker==3.2.0
      - pre-commit==4.2.0
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - protobuf==4.25.8
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==12.0.1
      - pybtex==0.25.1
      - pybtex-docutils==1.0.3
      - pycparser==2.23
      - pydata-sphinx-theme==0.16.1
      - pygments==2.19.2
      - pylint==3.0.3
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.1.3
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - readme-renderer==43.0
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - rfc3986==2.0.0
      - rich==14.2.0
      - rpds-py==0.29.0
      - ruff==0.12.4
      - safetensors==0.7.0
      - scikit-learn==1.3.2
      - scikit-survival==0.22.2
      - scipy==1.12.0
      - seaborn==0.13.2
      - secretstorage==3.5.0
      - sentry-sdk==2.46.0
      - setproctitle==1.3.7
      - six==1.17.0
      - smmap==5.0.2
      - snowballstemmer==3.0.1
      - soupsieve==2.8
      - sphinx==7.2.6
      - sphinx-book-theme==1.1.2
      - sphinx-math-dollar==1.2.1
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-bibtex==2.6.2
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - stack-data==0.6.3
      - sympy==1.14.0
      - tabulate==0.9.0
      - tenacity==9.1.2
      - termcolor==3.2.0
      - threadpoolctl==3.6.0
      - timm==1.0.22
      - tinycss2==1.4.0
      - tokenizers==0.13.3
      - tomlkit==0.13.3
      - torch==2.1.2
      - torchmetrics==0.11.4
      - torchsurv==0.1.5
      - torchvision==0.16.2
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.28.0
      - triton==2.1.0
      - twine==4.0.2
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - virtualenv==20.35.4
      - wandb==0.15.2
      - wcwidth==0.2.14
      - webencodings==0.5.1
      - wrapt==2.0.1
      - yacs==0.1.8
      - yarl==1.22.0
      - zipp==3.23.0
prefix: /nas-ctm01/homes/fmferreira/.conda/envs/ai4lungs
