directories:
  rootdir: /nas-ctm01/datasets/public/medical_datasets/lung_ct_datasets/nlst/preprocessed_data/protocol_5/2d/ws
  image_df_path: /nas-ctm01/homes/fmferreira/AI4LUNGS/lung_file_paths.csv
  cancer_path: /nas-ctm01/datasets/public/medical_datasets/lung_ct_datasets/nlst/cancer_info_final_mapped.csv
data:
  columns:
    pid: pid
    file_path: file_path

SEED: 22
test_size: 0.2

BATCH_SIZE_CPU: 32
BATCH_SIZE_GPU: 32
EPOCHS: 200
LEARNING_RATE: 1e-4

wandb:
  project: AI4H-Code
  entity: nlst
  name: test-embeddings

model_name: whole_slice
project: 3_type_scans

early_stopping:
  monitor: 'val_loss'
  patience: 50
  verbose: False
  mode: 'min' 
