_wandb:
    value:
        cli_version: 0.23.0
        e:
            lecp6htc8c0kwmnsps5u0xr30j27e2lz:
                codePath: test_embeddings.py
                codePathLocal: test_embeddings.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "491950960640"
                        used: "429829804032"
                email: francisco.sa.couto42@gmail.com
                executable: C:\Users\franc\miniconda3\envs\nlst_fm\python.exe
                git:
                    commit: 37a35de02ed3a7044c59417ef3f9c0bcd99499b3
                    remote: git@github.com:franciscosacouto/AI4LUNGS.git
                gpu: NVIDIA GeForce GTX 1650 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 1024
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce GTX 1650 Ti
                      uuid: GPU-252448af-3ef3-d0ed-3d42-d6cbd80052d5
                host: DESKTOP-20P2DRF
                memory:
                    total: "16913207296"
                os: Windows-10-10.0.26100-SP0
                program: C:\Users\franc\Desktop\AI4H-Code\test_embeddings.py
                python: CPython 3.11.11
                root: .
                startedAt: "2025-11-20T17:58:00.261362Z"
                writerId: lecp6htc8c0kwmnsps5u0xr30j27e2lz
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 5
                - 9
                - 41
                - 50
                - 53
                - 103
                - 106
            "2":
                - 1
                - 5
                - 9
                - 41
                - 50
                - 53
                - 103
                - 106
            "3":
                - 2
                - 7
                - 13
                - 16
                - 66
            "4": 3.11.11
            "5": 0.23.0
            "8":
                - 3
            "12": 0.23.0
            "13": windows-amd64
batch_size:
    value: 32
epochs:
    value: 300
learning_rate:
    value: 1e-05
model_type:
    value: MLP_Cox
